### ISSUE TITLE
Return data from database or record file using RESTful API 

### ISSUE THREAD

**Issue by kmubiin** [Sinar/telus#6]
This follows after #5 that combines data from SQLite database or MongoDB record file and data from API. The said issue must be solved beforehand, prior to returning data using RESTful API.

The following describes respective URLs with RESTful API in brief.

1. `/records/` - browse compiled releases
    * `/records/<id>` - view contract with id=`<id>`
2. `/persons/` - browse all persons (or list of persons?)
    * `/person/<id>` - view person with id=`<id>`
3. `/organizations/` - browse all organizations (or list of organizations?)
    * `/organization/<id>` - view organization with id=`<id>`
4. `/releases` - browse OCDS releases 
   * `releases/<id>` - view release with id=`<id>`

The RESTful API shall be provided by Flask extension called "Flask-RESTful".

**Comment by kaerumy** [comment]
Updated to match OCDS standards on release and records.. we will work on releases, organizations first

**Comment by kmubiin** [comment]
This issue was originally created based on Trello card given to me. Now deprecated.
